"""PeakSense - NO CODE setup."""

import json
import logging
import asyncio

from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.config_entries import ConfigEntry
from homeassistant.components.http import HomeAssistantView
from homeassistant.components.automation import automations_with_entity
from homeassistant.helpers.json import JSONEncoder

from .coordinator import PeakSenseCore
from .const import DOMAIN, CONF_POWER_METER, CONF_DEVICES

_LOGGER = logging.getLogger(__name__)


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Setup PeakSense."""
    
    core = PeakSenseCore()
    hass.data.setdefault(DOMAIN, {})
    hass.data[DOMAIN][entry.entry_id] = core
    hass.data[DOMAIN]["config"] = entry.data
    
    power_meter = entry.data.get(CONF_POWER_METER)
    devices = entry.data.get(CONF_DEVICES, [])
    
    # Register initial devices
    for device in devices:
        core.register_device(device.get("name"), device.get("standby_power", 0))
    
    # ========== AUTO-GENERATE AUTOMATION ==========
    await _create_automation(hass, power_meter)
    
    _LOGGER.info(f"PeakSense setup complete with {len(devices)} devices")

    # ========== Services ==========
    async def handle_update(call: ServiceCall):
        value = float(call.data.get("value", 0))
        core.process_value(value)

    hass.services.async_register(DOMAIN, "update", handle_update)

    async def handle_register_device(call: ServiceCall):
        name = str(call.data.get("name", "Unknown"))
        standby_power = float(call.data.get("standby_power", 0))
        core.register_device(name, standby_power)

    hass.services.async_register(DOMAIN, "register_device", handle_register_device)

    async def handle_record_signature(call: ServiceCall):
        event_id = int(call.data.get("event_id"))
        device_id = int(call.data.get("device_id"))
        events = core.storage.get_recent_events(1)
        if events and events[0]['id'] == event_id:
            core.record_signature(device_id, events[0])

    hass.services.async_register(DOMAIN, "record_signature", handle_record_signature)

    async def handle_delete_device(call: ServiceCall):
        device_id = int(call.data.get("device_id"))
        core.delete_device(device_id)

    hass.services.async_register(DOMAIN, "delete_device", handle_delete_device)

    # REST API
    hass.http.register_view(PeakSenseEventsView(core))
    hass.http.register_view(PeakSenseDevicesView(core))

    # Load sensors
    await hass.config_entries.async_forward_entry_setups(entry, ["sensor"])
    
    # Setup options listener
    entry.async_on_unload(entry.add_update_listener(_async_update_listener))

    return True


async def _create_automation(hass: HomeAssistant, power_meter: str):
    """Auto-create automation for feeding power values."""
    
    automation_config = {
        "alias": "PeakSense - Feed Power Meter",
        "description": "Automatically sends power readings to PeakSense (auto-generated)",
        "trigger": [{"platform": "state", "entity_id": power_meter}],
        "action": [
            {
                "service": "peaksense.update",
                "data": {"value": f"{{{{ states('{power_meter}') | float(0) }}}}"},
            }
        ],
        "mode": "queued",
    }
    
    try:
        # Check if automation already exists
        automations = await hass.async_add_executor_job(
            lambda: hass.config.path("automations.yaml")
        )
        
        # Create automation via service (this is the proper HA way)
        await hass.services.async_call(
            "automation",
            "create",
            {
                "name": "PeakSense - Feed Power Meter",
                "description": "Auto-generated by PeakSense",
                "trigger": {"platform": "state", "entity_id": power_meter},
                "action": {
                    "service": "peaksense.update",
                    "data": {"value": f"{{{{ states('{power_meter}') | float(0) }}}}"},
                },
            },
            blocking=False,
        )
        
        _LOGGER.info(f"Auto-created automation for power meter: {power_meter}")
    except Exception as e:
        _LOGGER.warning(f"Could not auto-create automation: {e}")
        _LOGGER.info(f"Please manually create automation with power meter: {power_meter}")


async def _async_update_listener(hass: HomeAssistant, entry: ConfigEntry):
    """Update listener for config changes."""
    await hass.config_entries.async_reload(entry.entry_id)


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload entry."""
    unload_ok = await hass.config_entries.async_unload_platforms(entry, ["sensor"])
    if unload_ok:
        hass.data[DOMAIN].pop(entry.entry_id)
    return unload_ok


class PeakSenseEventsView(HomeAssistantView):
    """REST: Events"""
    url = "/api/peaksense/events"
    name = "api:peaksense:events"
    requires_auth = True

    def __init__(self, core):
        self._core = core

    async def get(self, request):
        from aiohttp.web import Response
        try:
            events = self._core.storage.get_recent_events(100)
            return Response(text=json.dumps(events, cls=JSONEncoder), content_type="application/json")
        except Exception as e:
            return Response(text=json.dumps({"error": str(e)}), status=500)


class PeakSenseDevicesView(HomeAssistantView):
    """REST: Devices"""
    url = "/api/peaksense/devices"
    name = "api:peaksense:devices"
    requires_auth = True

    def __init__(self, core):
        self._core = core

    async def get(self, request):
        from aiohttp.web import Response
        try:
            devices = self._core.get_all_devices()
            return Response(text=json.dumps(devices, cls=JSONEncoder), content_type="application/json")
        except Exception as e:
            return Response(text=json.dumps({"error": str(e)}), status=500)
