DOMAIN = "peaksense"

# Thresholds
SPIKE_START_THRESHOLD = 800  # W
SPIKE_END_THRESHOLD = 300    # W

# Detection
MIN_CONFIDENCE = 0.75
SIMILARITY_THRESHOLD = 0.8

# Standby detection
STANDBY_DETECTION_DURATION = 120
STANDBY_SAMPLE_INTERVAL = 5

# Pattern matching
MIN_SAMPLES_FOR_PATTERN = 3

# Config
CONF_POWER_METER = "power_meter"
CONF_DEVICES = "devices"
