update:
  name: Update
  fields:
    value:
      name: Value
      selector:
        number:
          min: 0

register_device:
  name: Register Device
  fields:
    name:
      name: Device Name
      required: true
      selector:
        text:
    standby_power:
      name: Standby Power
      required: false
      default: 0
      selector:
        number:
          min: 0

record_signature:
  name: Record Signature
  fields:
    event_id:
      name: Event ID
      required: true
      selector:
        number:
          min: 1
    device_id:
      name: Device ID
      required: true
      selector:
        number:
          min: 1

label_event:
  name: Label Event
  fields:
    event_id:
      name: Event ID
      required: true
      selector:
        number:
          min: 1
    label:
      name: Label
      required: true
      selector:
        text:

provide_feedback:
  name: Provide Feedback
  fields:
    event_id:
      name: Event ID
      required: true
      selector:
        number:
          min: 1
    device_id:
      name: Device ID
      required: true
      selector:
        number:
          min: 1
    is_correct:
      name: Is Correct
      required: true
      selector:
        boolean:

update_device:
  name: Update Device
  fields:
    device_id:
      name: Device ID
      required: true
      selector:
        number:
          min: 1
    name:
      name: Name
      selector:
        text:
    standby_power:
      name: Standby Power
      selector:
        number:
          min: 0

delete_device:
  name: Delete Device
  fields:
    device_id:
      name: Device ID
      required: true
      selector:
        number:
          min: 1
