update:
  fields:
    value:
      selector:
        number:
          min: 0

register_device:
  fields:
    name:
      required: true
      selector:
        text:
    standby_power:
      selector:
        number:
          min: 0

record_signature:
  fields:
    event_id:
      required: true
      selector:
        number:
          min: 1
    device_id:
      required: true
      selector:
        number:
          min: 1

delete_device:
  fields:
    device_id:
      required: true
      selector:
        number:
          min: 1
